import pandas as pd

rx_notes = [
    "Carbidopa-Levodopa 25/100 mg 1 tab TID",
    "take 2 tablets of levodopa 100mg twice daily",
    "Ropinirole 0.25 mg x3/day",
    "amantadine 100 mg bid",
    "Carb/levo 25-100mg 1 tablet 3 times a day",
    "pramipexole 0.5mg qd",
    "rasagiline 1 mg daily",
    "rotigotine 4mg/24hr patch",
    "Stalevo 50/200/200 mg 1 tab tid",
    "Sinemet CR 25/100 mg 2 tabs at bedtime",
    "levodopa 100mg + carbidopa 25mg TID",
    "take 1.5 tabs of 25/100 mg carbidopa levodopa three times daily",
    "Amantadine HCL 100mg 2x daily",
    "Gocovri 137 mg cap nightly",
    "Osmolex ER 258mg once daily",
    "Inbrija 42 mg inhalation as needed",
    "apomorphine 2mg subcutaneous prn",
    "Neupro 6 mg patch q24 hours",
    "levodopa 200 mg morning and 100 mg evening",
    "carbidopa levodopa 25/100 mg 1 tab qid",
    "Rytary 48.75/195 mg 2 caps TID",
    "levodopa/carbidopa 100/25 mg tablet twice a day",
    "pramipexole 0.125 mg tid",
    "ropinerole 1mg three times daily",  # misspelling
    "rasagaline 1 mg daily",            # misspelling
    "amantadin 100 mg bid",             # misspelling
    "carbidopa levodopa 25/100 mg 1 tab tid prn",
    "levodopa 100 mg qam",
    "levodopa 100 mg qpm",
    "levodopa 100mg q4h",
    "carbidopa/levodopa 25/100 mg 1 tab every 4 hours",
    "take 1 tab 25/100 mg 5x/day",
    "levodopa 100 mg in the morning, 100 mg noon, 200 mg night",
    "rotigotine 2 mg/24hr transdermal system",
    "Neupro patch 4 mg daily",
    "Gocovri 68.5 mg capsules 2 at bedtime",
    "Sinemet 25/100 mg 1 tablet po tid",
    "Sinemet 25/100 mg 1 tablet po bid",
    "Sinemet 25/100 mg 1 tablet po qid",
    "levodopa 100 mg + entacapone 200 mg tid",
    "Stalevo 100/25/200 mg 1 tab tid",
    "Comtan 200 mg with each levodopa dose",
    "opicapone 50 mg nightly",
    "istradefylline 20 mg daily",
    "selegiline 5 mg bid",
    "safinamide 50 mg daily",
    "trihexyphenidyl 2 mg tid",
    "piribedil 50 mg bid",
    "levodopa 100 mg prn",
    "carbidopa levodopa 25/100 mg half tab tid",
    "levodopa 100 mg 1 tab in AM and 2 tabs in PM",
    "levodopa 100 mg 1 tab morning, 1 tab noon, 1 tab evening",
    "levodopa 100mg tabs x 3 daily",
    "levodopa 100 mg (1 tab) tid",
    "levodopa 100 mg tablet three times per day",
    "levodopa 100mg tablet once daily",
    "levodopa 100 mg 1 tablet qwk",  # weird frequency
    "levodopa 100 mg every other day",
    "levodopa 100 mg 2 tabs every morning",
    "levodopa 100 mg 2 tabs qam",
    "levodopa 100 mg 2 tabs qpm",
    "levodopa 100 mg 2 tabs qhs",
    "levodopa 100 mg 2 tabs nightly",
    "levodopa 100 mg 2 tabs bedtime",
    "levodopa 100 mg 2 tabs before sleep",
    "levodopa 100 mg 2 tabs at night",
    "levodopa 100 mg 2 tabs each evening",
    "levodopa 100 mg 2 tabs after dinner",
    "levodopa 100 mg 2 tabs in evening",
    "levodopa 100 mg 2 tabs q evening",
    "levodopa 100 mg 2 tabs in pm",
]

df = pd.DataFrame({"rx_note": rx_notes})
df.to_csv('/Users/emudr/PPMI_LEDD/data/simGPT/simGPT.csv')

